### ISSUE TITLE
Chunked cis-eQTL mapping loses genes

### ISSUE THREAD

**Issue by aksarkar** [qtltools/qtltools#11]
If I take GEUVADIS genes on chromosome 1 which have an annotation in ENSEMBL 75, I get 1564 genes.

If I then perform a permutation pass in 100 chunks using GEUVADIS genotypes on chromosome 1, I only get results for 1352 genes.

If I instead perform a permutation pass in 101 chunks, I get results for 1350 genes.

**Comment by rodrigoduarte88** [comment]
I've also observed this with my data.. fastqtl outputs files regarding the 100 chunks I specified.. but when I tried the "same" files with qtltools it spit only 86, raising the message that there weren't any variants in that chunk (very unlikely as I was working with imputed data). Does anyone know if qtltools has some sort of filter?

**Comment by dgarrimar** [comment]
In addition, when the number of chunks is smaller than the number of chromosomes, many genes are skipped in the output. `FastQTL` prevents this with an error call, while `QTLtools` does not.
