### ISSUE TITLE
NAs in covariates

### ISSUE THREAD

**Issue by heinin** [qtltools/qtltools#12]
Hi all,

How should NA values be indicated in the covariate file? "NA" causes an error (terminate called after throwing an instance of 'std::invalid_argument' what():  stof).

**Comment by clemgoub** [comment]
Same problem here!

**Comment by rodrigoduarte88** [comment]
It's a bit sad that this github has had no response from the developers...

**Comment by halitongen** [comment]
Fixed in version 1.2. Missing values in covariates should be NA.
