### ISSUE TITLE
Segmentation Fault + Core dumped

### ISSUE THREAD

**Issue by ivlachos** [qtltools/qtltools#13]
We were comparing fastQTL and QTLTools and as a toy example, we are using the original Geuvadis data.

FastQTL completes the nominal phase without an issue but we get a segmentation fault + core dump with QTL tools at the very first snp with or without --normal.

All snps and genes generate the same problem.  (removing snps and/or genes does not alter the behavior).

The error is:

**Processing phenotype [ENSG00000223875] [1/14]
  * #variants in cis = 3599
Segmentation fault (core dumped)**

The complete output of the call is:

QTLtools
  * Authors : Olivier DELANEAU / Halit ONGEN / Emmanouil DERMITZAKIS
  * Contact : olivier.delaneau@gmail.com / halit.ongen@unige.ch / Emmanouil.Dermitzakis@unige.ch
  * Webpage : https://qtltools.github.io/qtltools/
  * Version : 1.1
  * Date    : 09/05/2018 - 14:24:46
  * Citation: A complete tool set for molecular QTL discovery and analysis, https://doi.org/10.1101/068635

MAPPING QTL IN CIS
  * TASK: Report all nominal associations with p <= 0.01
  * Linear model: Phe ~ Var + Cov
  * Cis-window size is 1000000 bp
  * Chunk = [1/40]

Scanning phenotype data in [/work/Geuvadis/QTL/]
  * 578 phenotypes included

Read phenotype exclusion list [/work/Projects/GenT/QTL/blank_file.txt]
  * 0 phenotypes

Initialize random number generator
  * Built-in seed is 15112011
  * First Integer = 30554
  * First Double = 0.0126695

Reading sample list from [./GD462.GeneQuantRPKM.50FN.samplename.resk10.BED.gz]
  * #samples = 373

Read sample list from [./Geuvadis.Genotypes.chr22.vcf.gz]
  * #samples = 373

Reading sample list from [./Covariates.Geuvadis.BED]
  * #samples = 375

Merging sample sets from all input files
  * #files = 3
  * #samples in all files = 373
  * #samples NOT in all files (i.e. ignored) = 2

Reading phenotype data in [./GD462.GeneQuantRPKM.50FN.samplename.resk10.BED.gz]
  * #samples = 373]
  * target region [22:16100518-17179521]
  * 14 phenotypes included

Reading genotype data in [./Geuvadis.Genotypes.chr22.vcf.gz]
  * File format detected: VCF
  * target region [22:15100518-18179521]
  * 18374 variants included

Reading covariates in [./Covariates.Geuvadis.BED]
  * 7 covariates included

Residualize phenotypes for covariates
  * #covariates = 378

Match phenotypes to Normal distribution

Processing phenotype [ENSG00000223875] [1/14]
  * #variants in cis = 3599
Segmentation fault (core dumped)

**Comment by swvanderlaan** [comment]
I have had this issue as well. I found that one (or a combination) of two factors caused this: 

1. lack of memory
2. badly formatted files. It is absolutely critical to have for instance the way chromosomes are a noted (_e.g._ chromosome 1 as `01` or `chr1`) the _same_ accros files. And to have the inputfiles exactly as prescribed - the BED-files of the phenotypes in particular are different from `fastQTL`.

**Comment by rdalbanus** [comment]
I've had this issue when using eQTLs that were generated using other software. The problem was that the input file had **multiple SNPs per gene**, whereas QTLtools is expecting **one SNP per gene**. I solved that by selecting the most significant SNP per gene.

**Comment by halitongen** [comment]
Try using v1.3.1
