### ISSUE TITLE
--extract

### ISSUE THREAD

**Issue by swvanderlaan** [qtltools/qtltools#14]
In the [paper](https://www.nature.com/articles/ncomms15452) you refer to the ease by which QTLtools can extract data to facilitate plotting: 

> In addition, QTLtools also provides ways to easily extract subsets of data and therefore facilitate detailed inspection of particular eQTLs (Supplementary Fig. 11).

I love to work with this option, I suspect that this is `--extract`. But I can't find the how, either in the `qtltools --help` or on the site. So, how does `qtltools --extract` work? What is needed?

**Comment by halitongen** [comment]
Documented in v1.3.1
