### ISSUE TITLE
ERROR: Unrecognized QTLtools mode!

### ISSUE THREAD

**Issue by swvanderlaan** [qtltools/qtltools#15]
I noticed some flags that are not described on the website when running `--help`. The names and descriptions of some of the flags imply quite interesting features that I'd like to explore if possible. 

Are these functional and if so: how can we use them? I'm referring to: 

- `genrich`
- `extract`
- `rtc-union` 
- `ase`

Below an extract from the ``-help` call.

>qtltools_v1.1 --help
>
> QTLtools
>   * Authors : Olivier DELANEAU / Halit ONGEN / Emmanouil DERMITZAKIS
>   * Contact : olivier.delaneau@gmail.com / halit.ongen@unige.ch / Emmanouil.Dermitzakis@unige.ch
>   * Webpage : https://qtltools.github.io/qtltools/
>   * Version : 1.1
>   * Date    : 26/07/2018 - 15:23:22
>   * Citation: A complete tool set for molecular QTL discovery and analysis, https://doi.org/10.1101/068635
> 
> Usage:
>   QTLtools [mode] [options]
>   eg: QTLtools cis --help
> 
> Available modes:
>   bamstat   Calculate basic QC metrics for BAM/SAM
>   mbv       Match BAM to VCF
>   pca       Calculate principal components for a BED/VCF/BCF file
>   correct   Covariate correction of a BED file
>   cis       cis QTL analysis
>   trans     trans QTL analysis
>   fenrich   Functional enrichment for QTLs
>   fdensity  Functional density around QTLs
>   genrich   GWAS enrichment for QTLs
>   rtc       Regulatory Trait Concordance analysis
>   rtc-union Find the union of QTLs
>   extract   Data extraction mode
>   quan      Quantification mode
>   ase       Measure allelic imbalance at every het genotype
>

**Comment by halitongen** [comment]
These are currently intended for internal use and thus not documented
