### ISSUE TITLE
Makefile paths

### ISSUE THREAD

**Issue by mgandal** [qtltools/qtltools#17]
Makefile asks for custom HTSLIB, BOOST, RMath, etc paths but then rewrites them with `#UNIGE DESKTOP RELEASE VERSION` specific paths. Will automatically trigger errors unless these are manually changed

**Comment by Drbiology** [comment]
> Makefile asks for custom HTSLIB, BOOST, RMath, etc paths but then rewrites them with #UNIGE DESKTOP RELEASE VERSION specific paths. Will automatically trigger errors unless these are manually changed

I also have this problem

**Comment by halitongen** [comment]
Fixed in version 1.2
