### ISSUE TITLE
sample-run gives additional column, fails adjust-run

### ISSUE THREAD

**Issue by JulianRein** [qtltools/qtltools#21]
Hi,
when I run the tutorial ("How to run an approximate pass in trans?") on my data, the first / sample step return a "best-p-values"-file with 4 columns, the last being the variants with the lowest p-value. 
This leads to a failing adjust-run in step 2.
Removing the column manually and thus creating the format of the "best"-file as specified in the tutorial fixes things, but this cannot really be inferred from the error message 

> Reading null p-values in [trans.sample.1000perm.best.txt.gz]
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stof
Aborted (core dumped)

**Comment by halitongen** [comment]
Fixed in v1.3.1
