### ISSUE TITLE
permutation and nominal pass

### ISSUE THREAD

**Issue by cindywen96** [qtltools/qtltools#26]
Hi, I've been using FastQTL to map cis-QTL for molecular phenotypes. As QTLtools extends fastQTL in cis-QTL mapping, I'm posting my question here. 
Correct me if I'm wrong, but I just noticed that nominal pass is not outputting phenotypes without any variants in cis-window, while permutation pass is indeed outputting these phenotypes, with 0 in the number_of_variants column and NA in the following columns.
I'm wondering what is the rationale of doing so?
And a related question, is it correct to first remove the phenotypes with NAs, and then correct for multiple testing, since these phenotypes were not included in the testing I'd assume?

Thanks in advance.

**Comment by halitongen** [comment]
- Nominal pass reports associations below a certain threshold, thus phenotypes with no variants in cis fail this filter and are not reported; i.e. it was not designed to report everything in the first place.
- If all samples of a phenotype are missing, then this phenotype should obviously be excluded, If you have "a few" samples with missing values this is generally OK as we impute the missing values. However, determining what "a few" is, is up to the user.
Hope this helps
