### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by kelshmo** [qtltools/qtltools#30]
It looks like the [documentation hosted](https://qtltools.github.io/qtltools/) is not up-to-date with the new release. For example, I found a discrepancy in the documentation for discovering QTL in cis: The output columns are correctly [defined in the code here](https://github.com/qtltools/qtltools/blob/ba66d62ef441c2ab107844a19972afd25ad03afb/doc/QTLtools-cis.1#L119), but not on the site.

**Comment by halitongen** [comment]
I've no idea what the discrepency is, but as the website clearly indicates some of the pages are outdated and you need to refer to the man pages section of the website. From what I can tell there is no difference between the man page you refer to and the one on the website
