### ISSUE TITLE
Complie Error: [Makefile:204: bin/QTLtools] Error 1

### ISSUE THREAD

**Issue by YanXiaSKLMG** [qtltools/qtltools#33]
I am trying to install QTLtools in my Linux server, but get the following error:
g++ -std=c++0x obj/QTLtools.o obj/data.o obj/ase_main.o obj/ase_management.o obj/ase_read_blacklist.o obj/ase_read_fasta.o obj/ase_read_genotypes.o obj/ase_read_gtf.o obj/ase_read_sequences.o obj/ase_run_analyses.o obj/bamstat_main.o obj/bamstat_read_annotations.o obj/bamstat_read_bam.o obj/bamstat_write_output.o obj/cis_chunking.o obj/cis_collapse_phenotypes.o obj/cis_conditionnal_pass.o obj/cis_initilization.o obj/cis_learn_beta.o obj/cis_learn_dof.o obj/cis_main.o obj/cis_management.o obj/cis_nominal_pass.o obj/cis_permutation_pass.o obj/cis_read_covariates.o obj/cis_read_genotypes.o obj/cis_read_phenotypes.o obj/cis_read_thresholds.o obj/correct_main.o obj/correct_management.o obj/correct_processing.o obj/correct_read_covariates.o obj/extract_main.o obj/extract_managment.o obj/extract_read_data.o obj/extract_write.o obj/fdensity_main.o obj/fdensity_process.o obj/fdensity_read_annotation.o obj/fdensity_read_qtl.o obj/fenrich_main.o obj/fenrich_management.o obj/fenrich_process.o obj/fenrich_read_annotation.o obj/fenrich_read_qtl.o obj/fenrich_read_tss.o obj/genrich_binning_process.o obj/genrich_main.o obj/genrich_process.o obj/genrich_read_auxillliary_data.o obj/genrich_read_phenotypes.o obj/genrich_read_reference_genotypes.o obj/genrich_routines.o obj/gwas_analysis_pass.o obj/gwas_initilization.o obj/gwas_main.o obj/gwas_managment.o obj/gwas_read_covariates.o obj/gwas_read_phenotypes.o obj/match_main.o obj/match_managment.o obj/match_process.o obj/match_read_genotypes.o obj/match_read_sequences.o obj/pca_main.o obj/pca_management.o obj/pca_pca.o obj/pca_read_data.o obj/quan_main.o obj/quan_readBAM.o obj/quan_readGTF.o obj/quan_writeResults.o obj/quan_xxhash.o obj/rep_initilization.o obj/rep_main.o obj/rep_management.o obj/rep_nominal_pass.o obj/rep_read_covariates.o obj/rep_read_genotypes.o obj/rep_read_phenotypes.o obj/rep_read_qtls.o obj/rtc_chunking.o obj/rtc_collapse_phenotypes.o obj/rtc_common.o obj/rtc_gwas_cis.o obj/rtc_gwas_trans.o obj/rtc_initilization.o obj/rtc_main.o obj/rtc_management.o obj/rtc_mergeQTL_cis.o obj/rtc_mergeQTL_trans.o obj/rtc_read_covariates.o obj/rtc_read_genotypes.o obj/rtc_read_get_hotspots.o obj/rtc_read_phenotypes.o obj/rtc_sampling.o obj/trans_adjust.o obj/trans_analysis_pass.o obj/trans_chunking.o obj/trans_initilization.o obj/trans_learn_beta.o obj/trans_main.o obj/trans_managment.o obj/trans_read_covariates.o obj/trans_read_phenotypes.o obj/trans_read_samples.o obj/union_initilization.o obj/union_main.o obj/union_management.o obj/union_read_covariates.o obj/union_read_genotypes.o obj/union_read_get_hotspots.o obj/union_read_phenotypes.o obj/union_union.o /home/yxia/Tools/R-4.0.2/src/nmath/standalone/libRmath.a /home/yxia/Tools/htslib-1.10.2/libhts.a /usr/lib/x86_64-linux-gnu//libboost_iostreams.a /usr/lib/x86_64-linux-gnu//libboost_program_options.a -o bin/QTLtools -lz -lgsl -lbz2 -llzma -lgslcblas -lm -lpthread -lcurl -O3
/usr/bin/ld: /home/yxia/Tools/htslib-1.10.2/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha256@@OPENSSL_1_1_0'
/usr/bin/ld: //lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:204: bin/QTLtools] Error 1

any solutions?
Thanks inadvance

**Comment by asenabouth** [comment]
I too am having issues with compiling QTLtools in my Singularity image. I run into the same error as described above.

Here is my singularity recipe so you can replicate it:

```singularity
Bootstrap: docker
From: conda/miniconda3-centos7

%environment
    export LC_ALL=C
    export PYTHONPATH=/usr/local/envs/py36/lib/python3.6/site-packages
    alias cmake=cmake3
    export PATH=/opt:/usr/local:/usr/local/bin:$PATH
    export PERL5LIB=/opt/vcftools/src/perl/:$PERL5LIB

    %post
    # Update yum
    yum -y update

    # Activate conda pre-installed with bootstrap
    eval "$(command conda 'shell.bash' 'hook' 2> /dev/null)"
    conda update -y --prefix /usr/local conda

    # Define software versions
    PYTHON_VERSION=3.6
    JAVA_VERSION=1.8.0
    R_VERSION=3.6.3
    GCTA_VERSION=1.93.2beta
    HTSLIB_VERSION=1.12
    PLINK_VERSION=1.9
    PICARD_VERSION=2.23.8
    QTLTOOLS_VERSION=1.3.1
    INSTALL_DIR=/opt
    SOURCE_DIR=/src

    # Export to file that will be sourced by singularity
    echo """export PYTHON_VERSION=$PYTHON_VERSION""">> $SINGULARITY_ENVIRONMENT
    echo """export JAVA_VERSION=$JAVA_VERSION""">> $SINGULARITY_ENVIRONMENT
    echo """export R_VERSION=$R_VERSION""">> $SINGULARITY_ENVIRONMENT
    echo """export GCTA_VERSION=$GCTA_VERSION""">> $SINGULARITY_ENVIRONMENT
    echo """export HTSLIB_VERSION=$HTSLIB_VERSION""">> $SINGULARITY_ENVIRONMENT
    echo """export PLINK_VERSION=$PLINK_VERSION""">> $SINGULARITY_ENVIRONMENT
    echo """export PLINK_VERSION=$PICARD_VERSION""">> $SINGULARITY_ENVIRONMENT
    echo """export INSTALL_DIR=$INSTALL_DIR""">> $SINGULARITY_ENVIRONMENT
    echo """export SOURCE_DIR=$SOURCE_DIR""">> $SINGULARITY_ENVIRONMENT
    
    # Activate gcc7 that came pre-compiled in Centos7 OS
    yum -y install gcc gcc-c++
    yum -y groupinstall 'Development Tools'
    gcc --version
    source $SINGULARITY_ENVIRONMENT
    
    # Install wget and additional yum repositories
    yum -y install wget
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    yum-config-manager --enable "rhel-*-optional-rpms"

    yum -y install which
    # Install software
    yum -y install cmake3
    alias cmake=cmake3
    cmake --version

    # Install java
    yum -y install java-${JAVA_VERSION}-openjdk
    yum -y install java-${JAVA_VERSION}-openjdk-devel
    java -version

    # Create directory to install things into
    mkdir -p $INSTALL_DIR
    mkdir -p $SOURCE_DIR

    # Install dependancies for software installations
    yum -y install perl-core
    yum -y install perl-Data-Dumper 
    yum -y install zlib-devel 
    yum -y install curl-devel 
    yum -y install ncurses-devel
    yum -y install bzip2-devel
    yum -y install graphviz
    yum -y install graphviz-devel
    yum -y install libxml2-devel
    yum -y install devscripts
    yum -y install v8-devel
    yum -y install gsl-devel
    yum -y install cairo
    yum -y install libpng-devel
    yum -y install urw-fonts
    yum install xorg-x11-server-Xorg xorg-x11-xauth xorg-x11-apps -y
    yum -y install texlive 
    yum -y install texlive texlive-* --skip-broken
    yum -y install libtool
    yum -y install blas64
    yum -y install libX11-devel
    yum -y install libXt-devel
    yum -y install boost-devel
    yum -y install boost-static
    yum -y install gdal
    
    # Install openssl from source
    cd $SOURCE_DIR
    wget https://www.openssl.org/source/old/1.0.1/openssl-1.0.1u.tar.gz
    tar -xvfz openssl-1.0.1u.tar.gz
    cd openssl-1.0.1u
    ./config zlib
    make
    make install

    # Install icu4c
    cd $SOURCE_DIR
    wget https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-src.tgz
    tar xvfz icu4c-64_2-src.tgz
    cd icu/source
    ./configure
    make
    make install

    # Install pcre
    cd $SOURCE_DIR
    wget ftp://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz
    tar xzf pcre-8.44.tar.gz
    cd pcre-8.44
    ./configure --enable-utf8
    make 
    make install

    # Update SSH forwarding for X11
    cd /etc/ssh/
    cp ssh_config ssh_config_bkp
    awk 'NR==22 {$0="ForwardX11 yes"} 1' ssh_config > ssh_config
    systemctl restart sshd

    cd $SOURCE_DIR
    wget -c -N https://ftp.gnu.org/gnu/readline/readline-8.0.tar.gz
    tar -xzf readline-8.0.tar.gz
    cd readline-8.0/
    ./configure
    make
    make install
    
    cd /etc/ld.so.conf.d

    echo /usr/local/lib > locallib.conf
    echo /usr/local/lib64 > locallib64.conf
    echo /usr/lib64 > lib64.conf
    ldconfig

    # Install R
    cd $SOURCE_DIR
    wget https://cran.r-project.org/src/base/R-3/R-${R_VERSION}.tar.gz
    tar -xvzf R-${R_VERSION}.tar.gz
    cd R-${R_VERSION}/
    ./configure
    make
    make install

 
    # Install R match standalone
    cd src/nmath/standalone/
    make
    echo /src/R-3.6.3/src/nmath > /etc/ld.so.conf.d/rlib64.conf
    ldconfig
    make clean

    # Install htslib
    cd $INSTALL_DIR
    wget https://github.com/samtools/htslib/releases/download/$HTSLIB_VERSION/htslib-$HTSLIB_VERSION.tar.bz2
    tar -xjvf htslib-$HTSLIB_VERSION.tar.bz2
    cd htslib-$HTSLIB_VERSION
    ./configure --enable-libcurl
    make
    make install
    make clean
    
    cd $INSTALL_DIR
    rm htslib-$HTSLIB_VERSION.tar.bz2
    rm -rf htslib-$HTSLIB_VERSION

    # Install QTLtools
    cd $INSTALL_DIR
    git clone https://github.com/qtltools/qtltools.git
    cd qtltools

    # Update Makefile
    awk 'NR==4 {$0="BOOST_INC=/usr/include"} 1' Makefile > Makefile.old
    awk 'NR==5 {$0="BOOST_LIB=/usr/lib64"} 1' Makefile.old > Makefile
    awk 'NR==6 {$0="RMATH_INC=/usr/local/lib64/R/include"} 1' Makefile > Makefile.old
    awk 'NR==7 {$0="RMATH_LIB=/src/R-3.6.3/src/nmath/standalone"} 1'  Makefile.old > Makefile
    awk 'NR==8 {$0="HTSLD_INC=/usr/local/include"} 1' Makefile > Makefile.old
    awk 'NR==9 {$0="HTSLD_LIB=/usr/local/lib"} 1'  Makefile.old > Makefile

    # Configure and build
    make
```

I've also tried using the install available through yum (openssl-devel).

**Comment by halitongen** [comment]
try configuring htslib with the --disable-libcurl option before you run make on htslib:
./configure --disable-libcurl
make
