### ISSUE TITLE
Centos7.3 Install Error

### ISSUE THREAD

**Issue by Toseph** [qtltools/qtltools#4]
Everything in my makefile is configured correctly, but I run into an error at this step:
`make`
`g++ -std=c++0x obj/pca_pca.o obj/pca_read_data.o obj/pca_management.o obj/pca_main.o obj/gwas_analysis_pass.o obj/gwas_read_phenotypes.o obj/gwas_main.o obj/gwas_initilization.o obj/gwas_read_covariates.o obj/gwas_managment.o obj/union_read_phenotypes.o obj/union_read_covariates.o obj/union_management.o obj/union_initilization.o obj/union_main.o obj/union_read_get_hotspots.o obj/union_union.o obj/union_read_genotypes.o obj/correct_read_covariates.o obj/correct_main.o obj/correct_processing.o obj/correct_management.o obj/rep_read_genotypes.o obj/rep_read_phenotypes.o obj/rep_main.o obj/rep_read_qtls.o obj/rep_management.o obj/rep_nominal_pass.o obj/rep_initilization.o obj/rep_read_covariates.o obj/data.o obj/quan_printResults.o obj/quan_chunking.o obj/quan_management.o obj/quan_main.o obj/quan_readGTF.o obj/quan_readBAM.o obj/match_main.o obj/match_read_sequences.o obj/match_process.o obj/match_read_genotypes.o obj/match_managment.o obj/trans_analysis_pass.o obj/trans_read_covariates.o obj/trans_chunking.o obj/trans_read_phenotypes.o obj/trans_learn_beta.o obj/trans_initilization.o obj/trans_read_samples.o obj/trans_managment.o obj/trans_adjust.o obj/trans_main.o obj/cis_main.o obj/cis_conditionnal_pass.o obj/cis_learn_dof.o obj/cis_read_phenotypes.o obj/cis_permutation_pass.o obj/cis_chunking.o obj/cis_collapse_phenotypes.o obj/cis_read_genotypes.o obj/cis_read_covariates.o obj/cis_initilization.o obj/cis_management.o obj/cis_nominal_pass.o obj/cis_read_thresholds.o obj/cis_learn_beta.o obj/QTLtools.o obj/fdensity_read_qtl.o obj/fdensity_read_annotation.o obj/fdensity_process.o obj/fdensity_main.o obj/ase_read_sequences.o obj/ase_read_genotypes.o obj/ase_main.o obj/rtc_main.o obj/rtc_common.o obj/rtc_read_covariates.o obj/rtc_gwas_trans.o obj/rtc_sampling.o obj/rtc_mergeQTL_trans.o obj/rtc_management.o obj/rtc_read_phenotypes.o obj/rtc_chunking.o obj/rtc_read_genotypes.o obj/rtc_mergeQTL_cis.o obj/rtc_gwas_cis.o obj/rtc_initilization.o obj/rtc_collapse_phenotypes.o obj/rtc_read_get_hotspots.o obj/bamstat_read_bam.o obj/bamstat_write_output.o obj/bamstat_read_annotations.o obj/bamstat_main.o obj/fenrich_management.o obj/fenrich_read_qtl.o obj/fenrich_main.o obj/fenrich_read_tss.o obj/fenrich_read_annotation.o obj/fenrich_process.o obj/extract_read_data.o obj/extract_main.o obj/extract_managment.o obj/extract_write.o obj/genrich_routines.o obj/genrich_main.o obj/genrich_read_auxillliary_data.o obj/genrich_process.o obj/genrich_read_phenotypes.o obj/genrich_read_reference_genotypes.o obj/genrich_binning_process.o /nfs/sw/src/R-3.3.1/src/nmath/standalone/libRmath.a /nfs/sw/htslib/htslib-1.3.1//libhts.a /usr/lib64//libboost_iostreams.a /usr/lib64//libboost_program_options.a -o bin/QTLtools -Wl,-Bstatic -lz -lgsl -lblas -lbz2 -Wl,-Bdynamic -lm -lpthread  -O2`

THE ERROR: 
`/bin/ld: cannot find -lgsl`
`/bin/ld: cannot find -lbz2`

But I do have these libraries installed, 
`[root@myhost qtltools]# yum install gsl-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package gsl-devel-1.15-13.el7.x86_64 already installed and latest version
Nothing to do`
`[root@myhost qtltools]# yum install bzip2-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package bzip2-devel-1.0.6-12.el7.x86_64 already installed and latest version
Nothing to do`

How can I ensure /bin/ld is able to find these header files when they are already installed via yum?

**Comment by rodrigoduarte88** [comment]
Having the exact same issue.

**Comment by halitongen** [comment]
The static libraries of gsl and bz2 are missing in the system. This should be fixed in version 1.2 since now we are dynamically linking these libraries by default.
