### ISSUE TITLE
Deriving the beta-adjusted p-values from the fitted parameters

### ISSUE THREAD

**Issue by kwcurrin** [qtltools/qtltools#40]
Hello,

Is it possible to obtain the beta-approximated p-values using the nominal p-value and the two shape parameters using the pbeta function in R? I tried this for my data, but the p-values don't match. For example:
pbeta(0.00702837, 0.976548, 44.2766)

gives a value of 0.2788137, but the beta-adjusted p-value is listed as 0.342138. Do I need to set something different in the R function to get it to match? 

I was looking into this because I wanted to get locally corrected p-values for every tested SNP per gene. In the QTLTools manuscript, the methods for conditional analysis mentioned using the beta parameters for defining the nominal threshold per gene using qbeta, so I was wondering if pbeta could be used to get adjusted p-values for all tested SNPs for a gene. I wasn't sure if this would work however, given that the beta distribution models the distribution of the smallest value out of the given tests for a gene. It is unclear whether other p-values for the gene (not the smallest ones) would be accurately modeled by this beta distribution. Do you have other suggestions for locally correcting each SNP's p-value?

Thanks!

Kevin

**Comment by lw157** [comment]
Hi Kevin,
    The QTLtools provide a R script to define nominal p threshold per gene. The code is here: https://github.com/qtltools/qtltools/blob/master/scripts/qtltools_runFDR_cis.R.  This script is based on leading SNPs per gene and qbeta function.  
   Not sure it is suitable for pbeta for all SNP per gene. 

Liuyang

**Comment by kwcurrin** [comment]
Hi Liuyang,

Thanks for pointing me to that script.

Do you have advice for going the other way (deriving the beta-adjusted p-value) from the shape1, shape2, and nominal p-value? Based on the script you pointed me to, I added the below parameters to the pbeta function I shared in my original post:
ncp = 0, lower.tail = TRUE, log.p = FALSE)

However, the result is still the same, and the p-value I get from running pbeta doesn't match the one in the output file.

Thanks,

Kevin

**Comment by lw157** [comment]
Hi Kevin,
    I have not tried to derive the beta adjusted p value. Maybe you can refer to https://github.com/qtltools/qtltools/blob/master/src/mode_cis/cis_permutation_pass.cpp 

   line 168:  pval_bml = pbeta(getPvalue(best_nominal_correlation, dof_esti), beta_ml1, beta_ml2, 1, 0);
    
   The authors of QTLtools or fastQTL should know the exact answer.  Sorry for not further help.

Liuyang

**Comment by kwcurrin** [comment]
Hi Liuyang,

No problem, thanks for your help! I will close the issue.

Kevin
