### ISSUE TITLE
Error when number of variants in cis is 1

### ISSUE THREAD

**Issue by atfg** [qtltools/qtltools#6]
When running a cis analysis with permutations, if the phenotype has 0 or 1 variant in cis I get errors like this:

Processing phenotype [cg15822259] [53/356]
  * #variants in cis = 1
  * Best hit: [id=rs4247058, d=655153, pv=1, s=0.0000]
gsl: gamma.c:1249: ERROR: x too large to extract fraction part
Default GSL error handler invoked.
/tmp/1505236124.8291623: line 8: 14496 Aborted

It would be great to catch this error instead of crashing.

**Comment by kauralasoo** [comment]
I have exactly the same problem in version 1.1.

**Comment by ivlachos** [comment]
I just tried qtltools and stuck on the same issue.
It simply crashes and renders the run unusable.

**Comment by npanousis** [comment]
This happens when your phenotypes is 0 across all the samples. You should apply a filtering step before mapping

**Comment by swvanderlaan** [comment]
Are you (@atfg @npanousis @ivlachos @kauralasoo) using M-values or Beta-values when running these methylation QTL analyses? I get this error: https://github.com/qtltools/qtltools/issues/10. Which I don't understand. It might be related to the error you are getting.

**Comment by halitongen** [comment]
should be fixed in v1.3.1
